---
- name: setup a MQ development environment
  hosts: ubuntu
  vars:
    mq_qm_name: QM1
    mq_install_dev_objects: true
    mq_admin_password: password
    mq_enable_webserver: true
    mq_detect_download_installer: false # Installs last MQ Advanced Developper from repo IBM
    mq_local_installer: mqadv_dev931_ubuntu_x86-64.tar.gz
  roles:
   - jpcasas.ibm_mq_ansible_role