- name: setup a MQ development environment
  hosts: ubuntu
  vars:
    mq_qm_name: QM1
    mq_install_dev_objects: yes
    mq_admin_password: password
    mq_enable_webserver: yes
    mq_detect_download_installer: yes # Installs last MQ Advanced Developper from repo IBM
    # mq_local_installer: /vagrant/IBM_MQ_9.1.5_LINUX_X86-64.tar.gz
  roles:
    - jpcasas.ibm_mq_ansible_role